### ISSUE TITLE
Add force walk for players and NPCs

### ISSUE THREAD

**Issue by Zerotica** [Tomm0017/rsmod#128]
Add the ability to force walk through clipped areas (useful for things like agility).

**Comment by Tomm0017** [comment]
Addressed in https://github.com/Tomm0017/rsmod/commit/6918a34225cce6d47139d5eb9c07dad6b8a21275 & https://github.com/Tomm0017/rsmod/commit/6918a34225cce6d47139d5eb9c07dad6b8a21275

However, there is a caveat; there are specific situations where no-clipping will result in weird steps being taken until you teleport to your destination. I believe this is because the client will try to predict certain movement, though I do have to debug further to see if this is the case.
